"""initial_schema

Revision ID: f2e144e45503
Revises: 
Create Date: 2026-09-24 20:56:13.254541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e144e45503'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festivals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_pattern', sa.Text(), nullable=True),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('observance_details', sa.Text(), nullable=True),
    sa.Column('regional_variations', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'date', name='uq_festival_name_date')
    )
    with op.batch_alter_table('festivals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_festivals_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_festivals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_festivals_name'), ['name'], unique=False)

    op.create_table('panchanga_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('sunrise_time', sa.DateTime(), nullable=True),
    sa.Column('sunset_time', sa.DateTime(), nullable=True),
    sa.Column('noon_time', sa.DateTime(), nullable=True),
    sa.Column('moonrise_time', sa.DateTime(), nullable=True),
    sa.Column('moonset_time', sa.DateTime(), nullable=True),
    sa.Column('tithi_name', sa.String(length=100), nullable=True),
    sa.Column('tithi_end', sa.DateTime(), nullable=True),
    sa.Column('paksha', sa.String(length=20), nullable=True),
    sa.Column('nakshatra_name', sa.String(length=100), nullable=True),
    sa.Column('nakshatra_end', sa.DateTime(), nullable=True),
    sa.Column('yoga_name', sa.String(length=100), nullable=True),
    sa.Column('yoga_end', sa.DateTime(), nullable=True),
    sa.Column('karana_name', sa.String(length=100), nullable=True),
    sa.Column('karana_end', sa.DateTime(), nullable=True),
    sa.Column('brahma_muhurta_start', sa.DateTime(), nullable=True),
    sa.Column('abhijit_muhurta_start', sa.DateTime(), nullable=True),
    sa.Column('rahu_kaal_start', sa.DateTime(), nullable=True),
    sa.Column('rahu_kaal_end', sa.DateTime(), nullable=True),
    sa.Column('yamaganda_start', sa.DateTime(), nullable=True),
    sa.Column('yamaganda_end', sa.DateTime(), nullable=True),
    sa.Column('gulika_start', sa.DateTime(), nullable=True),
    sa.Column('gulika_end', sa.DateTime(), nullable=True),
    sa.Column('muhurta_count', sa.Integer(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'latitude', 'longitude', 'timezone', name='uq_panchanga_date_location_timezone')
    )
    with op.batch_alter_table('panchanga_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panchanga_cache_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_panchanga_cache_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_location_name')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_id'), ['id'], unique=False)

    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_type', name='uq_notification_user_event')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_preferences_id'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_id'))

    op.drop_table('notification_logs')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_id'))

    op.drop_table('locations')
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_device_tokens_id'))

    op.drop_table('device_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('panchanga_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panchanga_cache_id'))
        batch_op.drop_index(batch_op.f('ix_panchanga_cache_date'))

    op.drop_table('panchanga_cache')
    with op.batch_alter_table('festivals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_festivals_name'))
        batch_op.drop_index(batch_op.f('ix_festivals_id'))
        batch_op.drop_index(batch_op.f('ix_festivals_date'))

    op.drop_table('festivals')
    # ### end Alembic commands ###
